apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
      - name: hashgenerator
        image: sweatwork/dwk-app1:7401b1f1c76785422cc4e74ea78c6b32d1e5e08e249aa1797111456199996e57